### ISSUE TITLE
missing licence

### ISSUE THREAD

**Issue by Sickeroni** [neobrain/blobify#1]
for use in other projects a official licence would be beneficial.
Because `magic_enum` uses the [MIT Licence](https://github.com/Neargye/magic_enum/blob/master/LICENSE) I would suggest the same.

**Comment by neobrain** [comment]
Hey, thanks for reminding me!

The project will use something along the lines of MIT/BSD, possibly even boost license. I'll make sure to make a final call on this and add proper license information though, of course.

**Comment by neobrain** [comment]
... time flies by, huh? 🙈

I went for the boost license, which now resides in the repository: https://github.com/neobrain/blobify/blob/master/LICENSE
