### ISSUE TITLE
Compile error on clang 13.0.0

### ISSUE THREAD

**Issue by Centauria** [neobrain/blobify#11]
```
blobify/magic_enum/include/magic_enum.hpp:165:52: fatal error: instantiating fold expression with 257 arguments exceeded expression nesting limit of 256
  constexpr auto num_valid = ((valid[I] ? 1 : 0) + ...);
                             ~~~~~~~~~~~~~~~~~~~~~~^~~~
```

This is a known issue fixed on [Magic Enum v0.7.2](https://github.com/Neargye/magic_enum/releases/tag/v0.7.2)

Please update this dependency to the latest version [Magic Enum v0.7.3](https://github.com/Neargye/magic_enum/releases/tag/v0.7.3)

Thank you

**Comment by neobrain** [comment]
Presumably fixed since #14 updated the magic_enum module.
