### ISSUE TITLE
Compile Errors when building

### ISSUE THREAD

**Issue by bromeara** [neobrain/blobify#3]
When running make on the repository itself or when it is included in another project these errors are received. This is using the latest stable version of cmake(3.16.5) and version 7.5.0 of gcc which has full cpp 17 support.

In file included from blobify/include/blobify/exceptions.hpp:4:0,
                 from blobify/include/blobify/load.hpp:5,
                 from blobify/include/blobify/blobify.hpp:4,
                 from blobify/src/blobify.cpp:2:
blobify/include/blobify/detail/pmd_traits.hpp: In substitution of ‘template<class Data, auto ...PointersToMember> using pointed_member_type = std::remove_reference_t<decltype ((PointersToMember .* ... .*(declval<Data>)()))> [with Data = typename blob::detail::pmd_traits_t<PointerToMember>::parent_type; auto ...PointersToMember = {PointerToMember1, PointersToMember ...}]’:
blobify/include/blobify/store.hpp:154:102:   required from here
blobify/include/blobify/detail/pmd_traits.hpp:46:113: error: ‘PointerToMember1’ cannot be used as a member pointer, since it is of type ‘auto’
 using pointed_member_type = std::remove_reference_t<decltype((std::declval<Data>() .* ... .* PointersToMember))>;
                                                                                                                 ^
In file included from blobify/include/blobify/modify.hpp:5:0,
                 from blobify/include/blobify/blobify.hpp:5,
                 from blobify/src/blobify.cpp:2:
blobify/include/blobify/store.hpp: In function ‘constexpr void blob::lens_store(Storage&&, const Value&, blob::tag<ConstructionPolicy>)’:
blobify/include/blobify/store.hpp:157:34: error: ‘SpecificValueType’ was not declared in this scope
     detail::lens_store_to_offset<SpecificValueType, ConstructionPolicy, PointerToMember1, PointersToMember...>(storage, 0, value);
                                  ^~~~~~~~~~~~~~~~~
CMakeFiles/blobify-associated-sources.dir/build.make:62: recipe for target 'CMakeFiles/blobify-associated-sources.dir/src/blobify.cpp.o' failed
make[2]: *** [CMakeFiles/blobify-associated-sources.dir/src/blobify.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/blobify-associated-sources.dir/all' failed
make[1]: *** [CMakeFiles/blobify-associated-sources.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bromeara** [comment]
There were no compile errors when using clang 10 so I'm guessing it might be a bug with gcc 7.5.0 or implementation specific behavior. Will post findings

**Comment by neobrain** [comment]
According to https://godbolt.org/z/_YGXmk , gcc 7.5.0 should support this code (unless something at instantiation-site is tripping it up!). What's the output of `make VERBOSE=1`, and does the `-std=c++17` flag show up in there as expected?

**Comment by bromeara** [comment]
The compiler does seem to be invoking std=gnu++1z the deprecated 17 equivalent, I can post the output of VERBOSE=1 if you think that would be helpful. I am using ubuntu 18.04. As a side note, I have also tried this on both an x86 machine and ARM machine.

**Comment by bromeara** [comment]
It also builds with gcc 8, which was the simplest solution for us.
